<?xml version="1.0" encoding="utf-8"?>
<Project>

    <PropertyGroup>
        <!-- Target framework for all projects -->
        <TargetFramework>net10.0</TargetFramework>
        <!--
          Centralized version management:
          Define here shared framework and NuGet package versions
          to be consumed across all projects in the solution (single source of truth).
        -->

        <!-- Language & code quality -->
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <!-- Analyzers -->
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>

        <!-- Build quality -->
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    </PropertyGroup>

</Project>
